# Generated by Django 2.2.10 on 2020-03-18 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200317_1917'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='default',
            new_name='save_info',
        ),
    ]
